### ISSUE TITLE
Bug that causes crashing.

### ISSUE THREAD

**Issue by donq123** [belathus/eldritch_revolution#2] opened 2016-08-20 17:57 UTC
It all started when a quest gave me dispel and caused me to crash.
I can't load back into the world now cause I have dispel on me.

**Comment by belathus** [comment] 2016-08-20 20:08
Any idea which quest?

Assuming the dispel effect is a potion effect, you should be able to edit your player file to remove it using an NBT editor. I think that if you play SSP, that'll be the level.dat file.

**Comment by donq123** [comment] 2016-08-21 12:49
It is one of the gates quest i thinks, it procs a few times, just have to remove my armour.

**Comment by belathus** [comment] 2016-08-21 16:37
Gotcha. I will check it out. If it crashes me, too, we'll change that up.

**Comment by Divineaspect** [comment] 2016-08-22 15:49
This is caused by the potion IDs reassigning due to... something.
Manually fixing.

**Closed as completed** 2016-10-15 02:24 UTC
